//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class zensoftEntities : DbContext
    {
        public zensoftEntities()
            : base("name=zensoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblActivos> TblActivos { get; set; }
        public virtual DbSet<TblActivoSolicitado> TblActivoSolicitado { get; set; }
        public virtual DbSet<TblConsumibles> TblConsumibles { get; set; }
        public virtual DbSet<TblConsumibleSolicitado> TblConsumibleSolicitado { get; set; }
        public virtual DbSet<TblDepartamento> TblDepartamento { get; set; }
        public virtual DbSet<TblDependenciaOrganizativa> TblDependenciaOrganizativa { get; set; }
        public virtual DbSet<TblEmpleado> TblEmpleado { get; set; }
        public virtual DbSet<TblGrupo> TblGrupo { get; set; }
        public virtual DbSet<TblMovimiento> TblMovimiento { get; set; }
        public virtual DbSet<TblMovimientoConsumibles> TblMovimientoConsumibles { get; set; }
        public virtual DbSet<TblPlaza> TblPlaza { get; set; }
        public virtual DbSet<TblTraslado> TblTraslado { get; set; }
        public virtual DbSet<TblTrasladoActivo> TblTrasladoActivo { get; set; }
        public virtual DbSet<TblTrasladoConsumibles> TblTrasladoConsumibles { get; set; }
        public virtual DbSet<TblUbicacion> TblUbicacion { get; set; }
        public virtual DbSet<TblUnidadOrganizativa> TblUnidadOrganizativa { get; set; }
        public virtual DbSet<TblUsuario> TblUsuario { get; set; }
        public virtual DbSet<TblMovimientoActivo> TblMovimientoActivo { get; set; }
    
        public virtual ObjectResult<SP_CNS_ACTIVO_Result> SP_CNS_ACTIVO(string patrimonio)
        {
            var patrimonioParameter = patrimonio != null ?
                new ObjectParameter("patrimonio", patrimonio) :
                new ObjectParameter("patrimonio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_ACTIVO_Result>("SP_CNS_ACTIVO", patrimonioParameter);
        }
    
        public virtual ObjectResult<SP_CNS_ACTIVOS_Result> SP_CNS_ACTIVOS(string patriminio)
        {
            var patriminioParameter = patriminio != null ?
                new ObjectParameter("patriminio", patriminio) :
                new ObjectParameter("patriminio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_ACTIVOS_Result>("SP_CNS_ACTIVOS", patriminioParameter);
        }
    
        public virtual ObjectResult<SP_CNS_ACTIVOSDISPONIBLES_Result> SP_CNS_ACTIVOSDISPONIBLES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_ACTIVOSDISPONIBLES_Result>("SP_CNS_ACTIVOSDISPONIBLES");
        }
    
        public virtual ObjectResult<SP_CNS_ACTIVOSPRESTAMO_Result> SP_CNS_ACTIVOSPRESTAMO(Nullable<int> idMov)
        {
            var idMovParameter = idMov.HasValue ?
                new ObjectParameter("idMov", idMov) :
                new ObjectParameter("idMov", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_ACTIVOSPRESTAMO_Result>("SP_CNS_ACTIVOSPRESTAMO", idMovParameter);
        }
    
        public virtual ObjectResult<string> SP_CNS_CODDISPONIBLES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_CNS_CODDISPONIBLES");
        }
    
        public virtual ObjectResult<SP_CNS_CONSUMIBLE_FECHAS2_Result> SP_CNS_CONSUMIBLE_FECHAS2(Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta)
        {
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("desde", desde) :
                new ObjectParameter("desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("hasta", hasta) :
                new ObjectParameter("hasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_CONSUMIBLE_FECHAS2_Result>("SP_CNS_CONSUMIBLE_FECHAS2", desdeParameter, hastaParameter);
        }
    
        public virtual ObjectResult<SP_CNS_CONSUMIBLES_Result> SP_CNS_CONSUMIBLES(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_CONSUMIBLES_Result>("SP_CNS_CONSUMIBLES", codigoParameter);
        }
    
        public virtual ObjectResult<SP_CNS_CONSUMIBLES2_Result> SP_CNS_CONSUMIBLES2(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_CONSUMIBLES2_Result>("SP_CNS_CONSUMIBLES2", codigoParameter);
        }
    
        public virtual ObjectResult<SP_CNS_CONSUMIBLESDISPONIBLES_Result> SP_CNS_CONSUMIBLESDISPONIBLES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_CONSUMIBLESDISPONIBLES_Result>("SP_CNS_CONSUMIBLESDISPONIBLES");
        }
    
        public virtual ObjectResult<SP_CNS_CONSUMIBLESSOLICITUD_Result> SP_CNS_CONSUMIBLESSOLICITUD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_CONSUMIBLESSOLICITUD_Result>("SP_CNS_CONSUMIBLESSOLICITUD");
        }
    
        public virtual ObjectResult<SP_CNS_EMPLEADOS_Result> SP_CNS_EMPLEADOS(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_EMPLEADOS_Result>("SP_CNS_EMPLEADOS", cedulaParameter);
        }
    
        public virtual ObjectResult<SP_CNS_PRESTAMOSxEMPLEADO_Result> SP_CNS_PRESTAMOSxEMPLEADO(string cedula)
        {
            var cedulaParameter = cedula != null ?
                new ObjectParameter("cedula", cedula) :
                new ObjectParameter("cedula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_PRESTAMOSxEMPLEADO_Result>("SP_CNS_PRESTAMOSxEMPLEADO", cedulaParameter);
        }
    
        public virtual ObjectResult<SP_CNS_Usuarios_Result> SP_CNS_Usuarios(string grupo)
        {
            var grupoParameter = grupo != null ?
                new ObjectParameter("grupo", grupo) :
                new ObjectParameter("grupo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CNS_Usuarios_Result>("SP_CNS_Usuarios", grupoParameter);
        }
    
        public virtual int SP_INS_MOVACTIVO(string patrimonio)
        {
            var patrimonioParameter = patrimonio != null ?
                new ObjectParameter("patrimonio", patrimonio) :
                new ObjectParameter("patrimonio", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_MOVACTIVO", patrimonioParameter);
        }
    
        public virtual int SP_INS_MOVCONSUMIBLE(string codigo, Nullable<int> cantidad)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            var cantidadParameter = cantidad.HasValue ?
                new ObjectParameter("cantidad", cantidad) :
                new ObjectParameter("cantidad", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INS_MOVCONSUMIBLE", codigoParameter, cantidadParameter);
        }
    
        public virtual ObjectResult<SP_UO_List_Result> SP_UO_List(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_UO_List_Result>("SP_UO_List", codigoParameter);
        }
    }
}
